name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        working-directory: ./api  # Change to ./api directory
        run: |
          poetry install

      - name: Install Node.js dependencies
        working-directory: ./web  # Change to ./web directory
        run: npm install

      - name: Build Frontend
        working-directory: ./web 
        run: npm run build

      - name: Build and run Docker containers
        working-directory: ./docker 
        run: |
          docker compose -f docker-compose.middleware.yaml up -d --build

      - name: Apply database migrations (Flask)
        working-directory: ./api  # Change to ./api directory
        run: flask db upgrade

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_calm-island-05e944103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./web/build" # Output directory of frontend build
          api_location: "" # No direct deployment of API as it is managed by Docker
          output_location: ""

      - name: Stop Docker containers
        working-directory: ./docker 
        if: always() # Always run this step, even if previous steps fail
        run: docker compose -f docker-compose.middleware.yaml down

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_ISLAND_05E944103 }}
          action: "close"
